# Generated by Django 3.2.16 on 2023-01-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230117_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dunyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'foreignnews',
            },
        ),
    ]
